"""创建目标单位、来源追溯、联系人、商机及审核会话的第一版 PostGIS 结构。"""

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "20260805_0001"
down_revision = None
branch_labels = None
depends_on = None

organization_type = sa.Enum("高校", "研究院", "疾控", "食药", "环保", "公安", name="organization_type")
customer_status = sa.Enum("潜在客户", "商机客户", "已成交客户", name="customer_status")
review_status = sa.Enum("待核验", "已核验", "不纳入", name="review_status")
geocode_status = sa.Enum("待编码", "已定位", "低置信度", "待补地址", name="geocode_status")
opportunity_stage = sa.Enum("已识别", "资格确认", "方案/报价", "商务谈判", "已关闭失单", name="opportunity_stage")
evidence_kind = sa.Enum("官方名录", "院系/专业目录", "研究方向/实验室", "体育例外依据", "官方地址", "其他", name="evidence_kind")


def upgrade() -> None:
    """启用 PostGIS 并创建可追溯单位审核、销售关系和服务端会话表。"""

    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.create_table("admin_user", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("username", sa.String(80), nullable=False, unique=True), sa.Column("password_hash", sa.String(255), nullable=False), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))
    op.create_table("admin_session", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("admin_user.id", ondelete="CASCADE"), nullable=False), sa.Column("token_hash", sa.String(64), nullable=False, unique=True), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))
    op.create_table("organization", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("name", sa.String(255), nullable=False), sa.Column("normalized_name", sa.String(255), nullable=False), sa.Column("organization_type", organization_type, nullable=False), sa.Column("industry", sa.String(120)), sa.Column("customer_status", customer_status, nullable=False, server_default="潜在客户"), sa.Column("review_status", review_status, nullable=False, server_default="待核验"), sa.Column("inclusion_reason", sa.Text()), sa.Column("is_sports_exception", sa.Boolean(), nullable=False, server_default=sa.text("false")), sa.Column("parent_group", sa.String(255)), sa.Column("website", sa.String(500)), sa.Column("unified_social_credit_code", sa.String(18), unique=True), sa.Column("attributes", postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("notes", sa.Text()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))
    op.create_index("ix_organization_lookup", "organization", ["normalized_name", "organization_type", "review_status"])
    op.create_table("organization_site", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("organization_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("organization.id", ondelete="CASCADE"), nullable=False), sa.Column("site_name", sa.String(160)), sa.Column("raw_address", sa.String(500)), sa.Column("address", sa.String(500)), sa.Column("province", sa.String(60)), sa.Column("city", sa.String(60)), sa.Column("district", sa.String(80)), sa.Column("amap_adcode", sa.String(12)), sa.Column("geocode_status", geocode_status, nullable=False, server_default="待编码"), sa.Column("geocode_confidence", sa.Integer()), sa.Column("longitude", sa.Float()), sa.Column("latitude", sa.Float()), sa.Column("location", Geometry("POINT", srid=4326)), sa.Column("is_primary", sa.Boolean(), nullable=False, server_default=sa.text("true")), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))
    op.create_index("ix_organization_site_location", "organization_site", ["location"], postgresql_using="gist")
    op.create_index("ix_site_address_deduplicate", "organization_site", ["province", "city", "district", "address"])
    for column in ("province", "city", "district"):
        op.create_index(f"ix_organization_site_{column}", "organization_site", [column])
    op.create_table("organization_evidence", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("organization_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("organization.id", ondelete="CASCADE"), nullable=False), sa.Column("evidence_kind", evidence_kind, nullable=False), sa.Column("title", sa.String(255), nullable=False), sa.Column("source_url", sa.String(1000), nullable=False), sa.Column("published_at", sa.Date()), sa.Column("retrieved_at", sa.Date(), nullable=False), sa.Column("excerpt", sa.Text()))
    op.create_table("import_batch", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("name", sa.String(255), nullable=False), sa.Column("source_scope", sa.String(500), nullable=False), sa.Column("source_url", sa.String(1000)), sa.Column("imported_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("total_rows", sa.Integer(), nullable=False, server_default="0"), sa.Column("created_rows", sa.Integer(), nullable=False, server_default="0"), sa.Column("duplicate_rows", sa.Integer(), nullable=False, server_default="0"), sa.Column("geocode_failed_rows", sa.Integer(), nullable=False, server_default="0"), sa.Column("notes", sa.Text()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))
    op.create_table("import_row", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("batch_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("import_batch.id", ondelete="CASCADE"), nullable=False), sa.Column("raw_payload", postgresql.JSONB(), nullable=False), sa.Column("normalized_name", sa.String(255)), sa.Column("processing_status", sa.String(50), nullable=False, server_default="待处理"), sa.Column("organization_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("organization.id", ondelete="SET NULL")))
    op.create_table("duplicate_candidate", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("primary_organization_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("organization.id", ondelete="CASCADE"), nullable=False), sa.Column("candidate_organization_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("organization.id", ondelete="CASCADE"), nullable=False), sa.Column("confidence", sa.Integer(), nullable=False), sa.Column("rationale", sa.Text(), nullable=False), sa.Column("resolved_at", sa.DateTime(timezone=True)), sa.UniqueConstraint("primary_organization_id", "candidate_organization_id", name="uq_duplicate_pair"))
    op.create_table("organization_contact", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("organization_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("organization.id", ondelete="CASCADE"), nullable=False), sa.Column("name", sa.String(120), nullable=False), sa.Column("department", sa.String(160)), sa.Column("title", sa.String(160)), sa.Column("mobile", sa.String(40)), sa.Column("email", sa.String(254)), sa.Column("is_primary", sa.Boolean(), nullable=False, server_default=sa.text("false")), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")), sa.Column("notes", sa.Text()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))
    op.create_table("opportunity", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("organization_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("organization.id", ondelete="CASCADE"), nullable=False), sa.Column("title", sa.String(255), nullable=False), sa.Column("stage", opportunity_stage, nullable=False, server_default="已识别"), sa.Column("estimated_amount", sa.Numeric(14, 2)), sa.Column("ai_summary", sa.Text()), sa.Column("next_action", sa.Text()), sa.Column("next_action_at", sa.Date()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))
    op.create_table("sales_project", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("organization_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("organization.id", ondelete="CASCADE"), nullable=False), sa.Column("opportunity_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opportunity.id", ondelete="SET NULL")), sa.Column("name", sa.String(255), nullable=False), sa.Column("contract_amount", sa.Numeric(14, 2), nullable=False), sa.Column("signed_at", sa.Date()), sa.Column("project_detail", sa.Text()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))
    op.create_table("audit_log", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("organization_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("organization.id", ondelete="SET NULL")), sa.Column("actor_username", sa.String(80), nullable=False), sa.Column("action", sa.String(120), nullable=False), sa.Column("detail", postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))


def downgrade() -> None:
    """按依赖逆序移除首版表、枚举和 PostGIS 扩展之外的业务结构。"""

    for table in ("audit_log", "sales_project", "opportunity", "organization_contact", "duplicate_candidate", "import_row", "import_batch", "organization_evidence", "organization_site", "organization", "admin_session", "admin_user"):
        op.drop_table(table)
    for enum_type in (evidence_kind, opportunity_stage, geocode_status, review_status, customer_status, organization_type):
        enum_type.drop(op.get_bind(), checkfirst=True)
